from .caracterizacao_institucional import INDICATOR_SPECS as CARACTERIZACAO_INSTITUCIONAL_INDICATOR_SPECS
from .economica import INDICATOR_SPECS as ECONOMICA_INDICATOR_SPECS
from .sociocultural import INDICATOR_SPECS as SOCIOCULTURAL_INDICATOR_SPECS

__all__ = [
    "CARACTERIZACAO_INSTITUCIONAL_INDICATOR_SPECS",
    "ECONOMICA_INDICATOR_SPECS",
    "SOCIOCULTURAL_INDICATOR_SPECS",
]
