from __future__ import annotations

from .core import IndicatorSpec
from .dimensoes.caracterizacao_sociodemografica import (
    INDICATOR_SPECS as CARACTERIZACAO_SOCIODEMOGRAFICA_INDICATOR_SPECS,
)
from .dimensoes.caracterizacao_institucional import (
    INDICATOR_SPECS as CARACTERIZACAO_INSTITUCIONAL_INDICATOR_SPECS,
)
from .dimensoes.caracterizacao_territorio_ambiente import (
    INDICATOR_SPECS as CARACTERIZACAO_TERRITORIO_AMBIENTE_INDICATOR_SPECS,
)
from .dimensoes.caracterizacao_transformacao_digital import (
    INDICATOR_SPECS as CARACTERIZACAO_TRANSFORMACAO_DIGITAL_INDICATOR_SPECS,
)
from .dimensoes.capacidades_institucionais import INDICATOR_SPECS as CAPACIDADES_INSTITUCIONAIS_INDICATOR_SPECS
from .dimensoes.economica import INDICATOR_SPECS as ECONOMICA_INDICATOR_SPECS
from .dimensoes.meio_ambiente import INDICATOR_SPECS as MEIO_AMBIENTE_INDICATOR_SPECS
from .dimensoes.sociocultural import INDICATOR_SPECS as SOCIOCULTURAL_INDICATOR_SPECS

INDICATOR_SPECS: dict[str, IndicatorSpec] = {
    **CARACTERIZACAO_INSTITUCIONAL_INDICATOR_SPECS,
    **CARACTERIZACAO_SOCIODEMOGRAFICA_INDICATOR_SPECS,
    **CARACTERIZACAO_TERRITORIO_AMBIENTE_INDICATOR_SPECS,
    **CARACTERIZACAO_TRANSFORMACAO_DIGITAL_INDICATOR_SPECS,
    **CAPACIDADES_INSTITUCIONAIS_INDICATOR_SPECS,
    **ECONOMICA_INDICATOR_SPECS,
    **MEIO_AMBIENTE_INDICATOR_SPECS,
    **SOCIOCULTURAL_INDICATOR_SPECS,
}
