from .dados_abertos import INDICATOR_SPECS as DADOS_ABERTOS_SPECS
from .estrategia import INDICATOR_SPECS as ESTRATEGIA_SPECS
from .infraestrutura_hw_sw import INDICATOR_SPECS as INFRAESTRUTURA_HW_SW_SPECS
from .monitoramento import INDICATOR_SPECS as MONITORAMENTO_SPECS
from .servicos_aplicacoes import INDICATOR_SPECS as SERVICOS_APLICACOES_SPECS

INDICATOR_SPECS = {
    **DADOS_ABERTOS_SPECS,
    **ESTRATEGIA_SPECS,
    **INFRAESTRUTURA_HW_SW_SPECS,
    **MONITORAMENTO_SPECS,
    **SERVICOS_APLICACOES_SPECS,
}

__all__ = ["INDICATOR_SPECS"]
