from .cultura import INDICATOR_SPECS as CULTURA_SPECS
from .educacao import INDICATOR_SPECS as EDUCACAO_SPECS
from .gestao_desastres import INDICATOR_SPECS as GESTAO_DESASTRES_SPECS
from .inclusao_digital import INDICATOR_SPECS as INCLUSAO_DIGITAL_SPECS
from .inclusao_social import INDICATOR_SPECS as INCLUSAO_SOCIAL_SPECS
from .participacao_publica import INDICATOR_SPECS as PARTICIPACAO_PUBLICA_SPECS
from .saude import INDICATOR_SPECS as SAUDE_SPECS
from .seguranca_publica import INDICATOR_SPECS as SEGURANCA_PUBLICA_SPECS

INDICATOR_SPECS = {
    **CULTURA_SPECS,
    **EDUCACAO_SPECS,
    **GESTAO_DESASTRES_SPECS,
    **INCLUSAO_DIGITAL_SPECS,
    **INCLUSAO_SOCIAL_SPECS,
    **PARTICIPACAO_PUBLICA_SPECS,
    **SAUDE_SPECS,
    **SEGURANCA_PUBLICA_SPECS,
}

__all__ = ["INDICATOR_SPECS"]
