from .agua_esgoto import INDICATOR_SPECS as AGUA_ESGOTO_SPECS
from .dados_abertos import INDICATOR_SPECS as DADOS_ABERTOS_SPECS
from .habitacao import INDICATOR_SPECS as HABITACAO_SPECS
from .infraestrutura_conectividade import INDICATOR_SPECS as INFRAESTRUTURA_CONECTIVIDADE_SPECS
from .inovacao import INDICATOR_SPECS as INOVACAO_SPECS
from .residuos_solidos import INDICATOR_SPECS as RESIDUOS_SOLIDOS_SPECS
from .servicos_online_prefeitura import INDICATOR_SPECS as SERVICOS_ONLINE_PREFEITURA_SPECS
from .sistemas_tecnologia_gestao_urbana import INDICATOR_SPECS as SISTEMAS_TECNOLOGIA_GESTAO_URBANA_SPECS
from .transporte import INDICATOR_SPECS as TRANSPORTE_SPECS
from .urbanizacao_vias_publicas import INDICATOR_SPECS as URBANIZACAO_VIAS_PUBLICAS_SPECS

INDICATOR_SPECS = {
    **INFRAESTRUTURA_CONECTIVIDADE_SPECS,
    **INOVACAO_SPECS,
    **SERVICOS_ONLINE_PREFEITURA_SPECS,
    **SISTEMAS_TECNOLOGIA_GESTAO_URBANA_SPECS,
    **TRANSPORTE_SPECS,
    **AGUA_ESGOTO_SPECS,
    **DADOS_ABERTOS_SPECS,
    **HABITACAO_SPECS,
    **RESIDUOS_SOLIDOS_SPECS,
    **URBANIZACAO_VIAS_PUBLICAS_SPECS,
}

__all__ = ["INDICATOR_SPECS"]
