const singleChoiceQuestions = {
  7: {
    variavelSigla: "F7",
    options: [
      "Possui iluminação pública por telegestão e atende parte da cidade",
      "Possui iluminação pública por telegestão e atende toda a cidade",
    ],
  },
  11: {
    variavelSigla: "F11",
    options: [
      "Disponibiliza em parte dos estabelecimentos de saúde",
      "Disponibiliza em todos os estabelecimentos de saúde",
    ],
  },
  14: {
    variavelSigla: "F14",
    options: [
      "Sim, existe na prefeitura plataforma integrada para cidade inteligente em planejamento",
      "Sim, existe na prefeitura plataforma integrada para cidade inteligente em implementação",
      "Sim, existe na prefeitura plataforma integrada para cidade inteligente implementada",
    ],
  },
  23: {
    variavelSigla: "F23",
    options: [
      "Existe pelo menos uma pessoa articulando a elaboração de planos de TI",
      "Existe pessoal técnico qualificado, em alguma área da prefeitura, para elaborar planos de TI",
      "Existe departamento, setor ou área responsável pela infraestrutura de TI no município",
      "Não existe",
    ],
  },
  24: {
    variavelSigla: "F24",
    options: [
      "De 1 a 5 funcionários",
      "De 6 a 10 funcionários",
      "De 11 a 15 funcionários",
      "Acima de 16 funcionários",
      "Não existe equipe de TI",
    ],
  },
  28: {
    variavelSigla: "F28",
    options: [
      "Há sistemas que operam de forma vertical em todas as secretarias da prefeitura",
      "Há sistemas que operam de forma vertical em uma ou mais secretarias da prefeitura",
      "Há compartilhamento e integração de sistemas entre as secretarias da prefeitura, que permitem prestação de serviços em conjunto",
      "Há sistemas que operam de forma interoperável e transversal entre secretarias, que permitem prestação de serviços em conjunto",
      "Há uma plataforma que integra os sistemas e funciona como facilitadora de soluções colaborativas e participativas entre a gestão municipal e os munícipes",
      "Não existe integração de serviços entre as secretarias",
    ],
  },
  29: {
    variavelSigla: "F29",
    options: [
      "Os resultados do monitoramento e da avaliação são parcialmente disponibilizados ao público em portal ou outro meio digital pela prefeitura",
      "Os resultados do monitoramento e da avaliação são totalmente disponibilizados ao público em portal ou outro meio digital pela prefeitura",
      "Os resultados do monitoramento e da avaliação são totalmente disponibilizados ao público em portal ou outro meio digital pela prefeitura, em tempo real, de modo aberto e que permita o acompanhamento pelo cidadão",
      "Não são disponibilizados ao público",
    ],
  },
};

const multipleChoiceQuestions = {
  1: ["F1_1EAD", "F1_2APD", "F1_3MRP", "F1_4TC", "F1_5SOF", "F1_6TD"],
  2: ["F2GT", "F2_1DV", "F2_2AppCA"],
  3: ["F3CT", "F3_1PE", "F3_2AppCE", "F3_3SLD"],
  4: ["F4SVM", "F4_1SMS", "F4_2SVI", "F4_3SGPS", "F4_4DR"],
  5: ["F5SCB", "F5_1SCV", "F5_2CVE", "F5_3AppCP"],
  6: [
    "F6PTS",
    "F6_1PM10",
    "F6_2PM25",
    "F6_3CO",
    "F6_4SO2",
    "F6_5NOx",
    "F6_6NO",
    "F6_7NO2",
    "F6_11O3",
    "F6_8HCT",
    "F6_9HCnM",
    "F6_10CH4",
  ],
  8: ["F8WS", "F8_1AppP", "F8_2PPO", "F8_3PPP"],
  9: ["F9FUM", "F9_1VV", "F9_2TEMP", "F9_3PRECPLUV"],
  10: [
    "F10CRGCULT",
    "F10_1ED",
    "F10_2PCPRJCULT",
    "F10_3INSCPROJCULT",
    "F10_4LINCPCULT",
    "F10_5MAPCULT",
  ],
  12: ["F12AC", "F12_1AE", "F12_2REXAM", "F12_3VPE", "F12_4IEM"],
  13: [
    "F13INFBAS",
    "F13_1ECCR",
    "F13_2TECINF",
    "F13_3ROBPROG",
    "F13_4TRABEMPREE",
    "F13_5PPPFORM",
    "F13_6TELEC",
  ],
  15: ["F15MLP", "F15_1COLGPS", "F15_2GCRES", "F15_3DFRESApp"],
  16: [
    "F16PATVCUL",
    "F16_1INFATVCULT",
    "F16_2INFCULT",
    "F16_3PUBLESTCULT",
    "F16_4CATBIBL",
    "F16_5TRAMVIDSTR",
    "F16_6VVIRT",
    "F16_7ACSSDIG",
  ],
  17: [
    "F17ASSSOC",
    "F17_1CULT",
    "F17_2DEINOV",
    "F17_3EDU",
    "F17_4GEST",
    "F17_5MA",
    "F17_6OIFRA",
    "F17_7PURB",
    "F17_8SAUD",
    "F17_9SEG",
    "F17_10TRANSP",
    "F17_11TUR",
  ],
  18: ["F18PDIR", "F18_1PDTIC", "F18_2LOPPA", "F18_3LAI", "F18_5PECI", "F18_4NHAPLAN"],
  19: ["F19LPRITIC", "F19_1IETIEXP", "F19_2MLIOTBD", "F19_3POSTHSOLTEC", "F19_4NRATIV"],
  20: [
    "F20GMUN",
    "F20_1GEST",
    "F20_2GFED",
    "F20_3SPRIV",
    "F20_4SCORG",
    "F20_5CIDMUNIC",
    "F20_6UIPESQ",
    "F20_7CVER",
    "F20_8ESSILOC",
    "F20_9AGFOMPUBL",
    "F20_10FINPRIV",
    "F20_11ORGINT",
    "F20_12CONSPRIV",
    "F20_13NENA",
  ],
  21: [
    "F21PROCFORMPLAMET",
    "F21_1PRODIGDISP",
    "F21_2PLANDISPINDIMP",
    "F21_3AVRESUKPROCPLAMET",
    "F21_4NACINTIC",
  ],
  22: ["F22DEPTGMUN", "F22_1CONSCIND", "F22_2COMESP", "F22_3CONSPRIVTERC", "F22_4NRESP"],
  25: [
    "F25EPRTIPREF",
    "F25_1PRATPADRTIPREF",
    "F25_2PROCFORMCONTTI",
    "F25_3ACESPFORNEXT",
    "F25_4APRIMTIPSERV",
    "F25_5NADPRSTPREF",
  ],
  26: [
    "F26DCPROP",
    "F26_1NUV",
    "F26_2SERVPROP",
    "F26_3COMPCONCREDE",
    "F26_4COMPNCONECTREDE",
    "F26_5COMPPESS",
    "F26_6ARQFISICO",
    "F26_7NARMDADO",
  ],
  27: [
    "F27AELETRDIGDOC",
    "F27_1CERTDIGFPAGTO",
    "F27_2SUPORENESERVCENTR",
    "F27_3BACKUP",
    "F27_4INDINVSPAM",
    "F27_5CONTRSWINST",
    "F27_6SAREDE",
    "F27_7RESTRACFIS",
    "F27_8NPRAST",
  ],
};

const questionIds = [...Object.keys(singleChoiceQuestions), ...Object.keys(multipleChoiceQuestions)]
  .map(Number)
  .sort((a, b) => a - b);

module.exports = {
  multipleChoiceQuestions,
  questionIds,
  singleChoiceQuestions,
};
